=== Ultraschall/ultraschall-whitepapers/PodMeta-Metadata_Exchange/v1/Episode.schema.json
{
  "$id": "https://example.com/episode.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Episode",
  "type": "object",
  "description": "Episode JSON Schema",
  "examples": [],
  "properties": {
    "title": {
      "type": "string"
    },
    "subtitle": {
      "type": "string"
    },
    "summary": {
      "type": "string"
    },
    "number": {
      "type": "string"
    },
    "season": {
      "type": "string"
    },
    "release_date": {
      "type": "string",
      "description": "ISO 8061 (see https://de.wikipedia.org/wiki/ISO_8601)"
    },
    "language": {
      "type": "string"
    },
    "explicit": {
      "type": "string"
    },
    "uuid": {
      "type": "string"
    },
    "shownotes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "shownotes": {
            "$ref": "/Shownote.schema"
          }
        }
      }
    },
    "contributors": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "contributors": {
            "$ref": "/Contributor.schema"
          }
        }
      }
    }
  }
}

=== Ultraschall/ultraschall-whitepapers/PodMeta-Metadata_Exchange/v1/SampleFiles/Episode.json
{
    "title": "Ein Blick auf die Publisher Beta 4",
    "subtitle": "Eine neue Version in den Startlöchern",
    "summary": "Der Podlovers-Podcast meldet sich zurück. Alex, Dirk, Eric und Martin geben Euch einen Einblick in die Beta der neuen Version und stellen die wichtigsten Neuerungen vor. Hört rein und testet dann gerne mit.",
    "number": "23",
    "release_date": "20230730T18:22:17+02:00",
    "language": "de",
    "explicit": "no",
    "contributors": [
        {
            "name": "Dirk",
            "description": "Developer",
            "role": "Host"
        },
        {
            "name": "Eric",
            "description": "Developer",
            "role": "Host"
        }
    ],
    "shownotes": [
        {
            "title": "Install Podlove Publisher Beta",
            "description": "How to install the beta",
            "timestamp": "00:04:23",
            "url": "https://www.youtube.com/watch?v=lMHFyHPMn4Q"
        }
    ]
}
