=== Ultraschall/ultraschall-whitepapers/PodMeta-Metadata_Exchange/v1/Podcast.schema.json
{
  "$id": "https://example.com/podcast.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Podcast",
  "type": "object",
  "description": "Podcast JSON Schema",
  "properties": {
    "title": {
      "type": "string"
    },
    "subtitle": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "mail": {
      "type": "string"
    },
    "website": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "url": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== Ultraschall/ultraschall-whitepapers/PodMeta-Metadata_Exchange/v1/SampleFiles/Podcast.json
{
    "title": "Podlovers",
    "subtitle": "",
    "description": "Der Podlove Entwickler:innen Podcast",
    "mail": "test@example.com",
    "website" : [
        {
            "name" : "homepage",
            "description" : "Homepage podlovers",
            "url" : "https://podlovers,org"
        },
        {
            "name" : "podlove",
            "description": "Podlove Homepage",
            "url" : "https://podlove.org"
        }
    ]
}
